import {AlertCircle,CarFront,Check,Clock3,Inbox,WifiOff} from 'lucide-react';
import type {ReactNode} from 'react';
import {faNum} from '../lib/format';
export function PageHeader({title,description,action,eyebrow}:{title:string;description:string;action?:ReactNode;eyebrow?:string}){return <header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div>{eyebrow&&<p className="eyebrow mb-2">{eyebrow}</p>}<h1 className="page-title">{title}</h1><p className="muted mt-2 max-w-2xl text-sm leading-7">{description}</p></div>{action&&<div className="shrink-0">{action}</div>}</header>}
export function MatchScore({score=0,compact=false}:{score?:number;compact?:boolean}){const label=score>=90?'تطابق عالی':score>=75?'تطابق بالا':'تطابق متوسط';return <div className={`inline-flex items-center gap-2 rounded-full border border-emerald-600/15 bg-emerald-500/[.08] font-semibold text-emerald-700 dark:text-emerald-300 ${compact?'px-2.5 py-1 text-xs':'px-3 py-2 text-sm'}`}><span className="grid h-5 w-5 place-items-center rounded-full bg-emerald-600 text-[10px] text-white"><Check size={12}/></span><span>{faNum(score)}٪{!compact&&` · ${label}`}</span></div>}
export function StatusBadge({status}:{status:string}){const map:Record<string,[string,string,ReactNode]>={success:['موفق','text-emerald-700 bg-emerald-500/10 dark:text-emerald-300',<Check size={13}/>],failed:['ناموفق','text-red-700 bg-red-500/10 dark:text-red-300',<AlertCircle size={13}/>],partial:['نیمه‌کامل','text-amber-700 bg-amber-500/10 dark:text-amber-300',<AlertCircle size={13}/>],running:['در حال اجرا','text-blue-700 bg-blue-500/10 dark:text-blue-300',<Clock3 size={13}/>]};const [label,cls,icon]=map[status]??[status,'muted bg-black/5',null];return <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold ${cls}`}>{icon}{label}</span>}
export function EmptyState({title,description,action,icon='empty'}:{title:string;description:string;action?:ReactNode;icon?:'empty'|'car'|'offline'}){const Icon=icon==='car'?CarFront:icon==='offline'?WifiOff:Inbox;return <div className="card grid min-h-72 place-items-center p-8 text-center"><div className="max-w-md"><div className="mx-auto grid h-16 w-16 place-items-center rounded-2xl bg-wine/[.08] text-wine"><Icon size={28}/></div><h2 className="mt-5 text-lg font-semibold">{title}</h2><p className="muted mt-2 text-sm leading-7">{description}</p>{action&&<div className="mt-6">{action}</div>}</div></div>}
export function ErrorState({retry}:{retry?:()=>void}){return <div className="rounded-2xl border border-red-500/20 bg-red-500/[.06] p-5"><div className="flex items-start gap-3"><AlertCircle className="mt-0.5 text-red-600" size={20}/><div><p className="font-semibold">در دریافت اطلاعات مشکلی پیش آمد</p><p className="muted mt-1 text-sm">اتصال خود را بررسی کنید و دوباره تلاش کنید.</p>{retry&&<button className="mt-3 text-sm font-semibold text-red-700" onClick={retry}>تلاش دوباره</button>}</div></div></div>}
export function PageSkeleton(){return <div className="space-y-6" aria-label="در حال بارگذاری"><div className="skeleton h-8 w-48"/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map(x=><div key={x} className="card p-5"><div className="skeleton h-11 w-11"/><div className="skeleton mt-8 h-8 w-24"/><div className="skeleton mt-3 h-4 w-32"/></div>)}</div></div>}
