# Generated by Django 4.2.16 on 2026-08-20 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("brand", models.CharField(blank=True, max_length=80)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("trim", models.CharField(blank=True, max_length=80)),
                ("min_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("max_year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("min_price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("max_price", models.PositiveBigIntegerField(blank=True, null=True)),
                ("min_mileage", models.PositiveIntegerField(blank=True, null=True)),
                ("max_mileage", models.PositiveIntegerField(blank=True, null=True)),
                ("cities", models.JSONField(blank=True, default=list)),
                ("districts", models.JSONField(blank=True, default=list)),
                ("colors", models.JSONField(blank=True, default=list)),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[("automatic", "اتوماتیک"), ("manual", "دنده\u200cای")],
                        max_length=20,
                    ),
                ),
                ("body_condition", models.CharField(blank=True, max_length=80)),
                ("description_keywords", models.JSONField(blank=True, default=list)),
                ("excluded_keywords", models.JSONField(blank=True, default=list)),
                ("telegram_enabled", models.BooleanField(default=True)),
                ("notify_once", models.BooleanField(default=True)),
                ("minimum_match_score", models.PositiveSmallIntegerField(default=70)),
                ("crawl_interval_minutes", models.PositiveIntegerField(default=60)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="search_profiles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
