# Generated by Django 4.2.16 on 2026-08-20 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("searches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(default="divar", max_length=30)),
                ("external_id", models.CharField(db_index=True, max_length=160)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(max_length=700)),
                (
                    "canonical_url",
                    models.URLField(blank=True, db_index=True, max_length=700),
                ),
                ("image_urls", models.JSONField(blank=True, default=list)),
                ("thumbnail_url", models.URLField(blank=True, max_length=700)),
                (
                    "price",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("mileage", models.PositiveIntegerField(blank=True, null=True)),
                ("brand", models.CharField(blank=True, max_length=80)),
                ("model", models.CharField(blank=True, max_length=80)),
                ("trim", models.CharField(blank=True, max_length=80)),
                ("color", models.CharField(blank=True, max_length=40)),
                ("transmission", models.CharField(blank=True, max_length=30)),
                ("body_condition", models.CharField(blank=True, max_length=80)),
                ("city", models.CharField(blank=True, max_length=80)),
                ("district", models.CharField(blank=True, max_length=120)),
                ("seller_type", models.CharField(blank=True, max_length=60)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "discovered_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-discovered_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("match_score", models.PositiveSmallIntegerField()),
                ("matched_fields", models.JSONField(default=dict)),
                ("failed_fields", models.JSONField(default=list)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="listings.listing",
                    ),
                ),
                (
                    "search_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="searches.searchprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-detected_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="listing",
            constraint=models.UniqueConstraint(
                fields=("provider", "external_id"), name="unique_provider_listing"
            ),
        ),
        migrations.AddConstraint(
            model_name="searchmatch",
            constraint=models.UniqueConstraint(
                fields=("search_profile", "listing"), name="unique_search_listing_match"
            ),
        ),
    ]
